spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev  #开发环境
  application:
    name: microservicecloud-config-hczy-dev  
---
spring:
  profiles: test  #测试环境
  application:
    name: microservicecloud-config-hczy-test   
    # 以utf-8 形式保存   