spring:
  profiles:
    active:
    - test
---    
server:
  port: 8002

spring:
   profiles: dev
   application: 
    name: microservicecloud-dept-bus                            # 注册进eureka的名字


eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/      
  instance:
    instance-id: microservicecloud-config-dept8003
    prefer-ip-address: true     #访问路径可以显示IP地址     

info: 
  app.name: springcloud-test
  company.name: www.hczy.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 8001

spring:
   profiles: test
   application: 
    name: microservicecloud-dept-bus                            # 注册进eureka的名字

 

eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/      
  instance:
    instance-id: microservicecloud-config-dept8001
    prefer-ip-address: true     #访问路径可以显示IP地址     

info: 
  app.name: springcloud-test
  company.name: www.hczy.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$    
    
